<?php 
    $this->inlineScript()->prependFile($this->basePath() . '/assets/mot-ob/js/addrow.js');
    $this->headLink()->prependStylesheet($this->basePath() . '/assets/datatables/media/css/jquery.dataTables_themeroller.css')
            ->prependStylesheet($this->basePath() . '/assets/datatables/extras/TableTools/media/css/TableTools.css')
            ->prependStylesheet($this->basePath() . '/assets/datatables/media/css/jquery.dataTables.min.css')
            ->prependStylesheet($this->basePath() . '/assets/jquery-ui/themes/humanity/theme.css')
            ->prependStylesheet($this->basePath() . '/assets/jquery-ui/themes/humanity/jquery-ui.min.css');
    
    
    $this->inlineScript()
            ->prependFile($this->basePath('assets/mot-ob/js/datatable.js'))
            ->prependFile($this->basePath('assets/datatables/extras/TableTools/media/js/TableTools.js'))
            ->prependFile($this->basePath('assets/datatables/extras/TableTools/media/js/ZeroClipboard.js'))
            ->prependFile($this->basePath('assets/datatables/media/js/jquery.dataTables.min.js'))
            ->prependFile($this->basePath('assets/jquery-ui/jquery-ui.min.js'));
    
    $this->inlineScript()->captureStart();
    echo '
        $(function() {
            $( "#accordion" ).accordion();
        }); 
        ';
    $this->inlineScript()->captureEnd();
?>
<div class="pageheader">
     <div class="media">
         <div class="pageicon pull-left">
             <i class="fa fa-line-chart"></i>
         </div>
         <div class="media-body" style="padding-left: 5px">
             <ul class="breadcrumb">
                 <li>
                     <a href="<?php echo $this->url('mot');?>"><i class="glyphicon glyphicon-home"></i></a>
                 </li>
                 <li><a href="#">Official Business</a></li>
                 <li>Report</li>
             </ul>
             <h4>OB Report</h4>
         </div>
     </div>
</div>
<div class="contentpanel">
        <div>
        <div class="row">
        <select>
            <option>Branch</option>
        </select>
        <select>
            <option>Employee</option>
        </select>

        &nbsp;From <input type="date">&nbsp;<i class="fa fa-calendar fa-2x"></i>
        &nbsp;To <input type="date">&nbsp;<i class="fa fa-calendar fa-2x"></i>
        &nbsp;<button class="btn">View</button>
        </div>
        <br>
      
        <div class="table-responsive">
            <?php 
            foreach ($this->result AS $data) 
            {
                echo "<h3> {$data['title']} </h3>"
                . "<div> {$this->DataTables($data['name'], $data['header'], $data['data'])} </div>";
            } ?>
    </div>
    </div>
</div>
